export const Globals = {
    translate : {
        'Menu' : 'Meni',
        'About Us' : 'O nama',
        'Location' : 'Lokacija',
        'Online order' : 'Naruči online',
        "Profile":"Profil",
        "Logout":"Izlogujte se",
        "Dashboard" : "Komandna tabla",
        'Log in':'Ulogujte se',
        'Register': 'Registrujte se',
        "Create Your Web Page":"Kreirajte Vašu Stranicu",
        "You logged in!":"Ulogovani ste!",
        "CREATE":"ZAPOČNI",
        "Dashboard":"Komandna Tabla",
        "Type Restaurant Title":"Unesite naziv svog Restorana",
        "Choose city":"Odaberite opštinu",
        "Restaurant title":"Naziv restorana",
  "Sandwiches": "Sendviči",
  "Food truck": "Kombi sa hranom",
  "Pub": "Pab",
  "Bakery": "Pekara",
  "Pizza": "Pica",
  "Deli": "Delikates",
  "Fine dining": "Gurmanski restoran",
  "Buffet": "Bife",
  "Bar": "Bar",
  "Bar and Brewery": "Bar i pivara",
  "Fast food": "Brza hrana",
  "Cafeteria": "Kantina",
  "BBQ (Barbecue)": "Roštilj",
  "Gyros": "Giros",
  "Breakfast": "Doručak",
  "Lunch": "Ručak",
  "Dinner": "Večera",
  "Dine-in": "Jedenje u restoranu",
  "Drive-through": "Prolazna usluga",
  "Drinks": "Pića",
  "Kebab": "Kebab",
  "Indian": "Indijska",
  "Fish": "Riba",
  "Pasta": "Pasta",
  "Italian": "Italijanska",
  "International": "Internacionalna",
  "Mexican": "Meksička",
  "Thai": "Tajska",
  "Chinese": "Kineska",
  "Japanese": "Japanska",
  "French": "Francuska",
  "French Fries": "Pomfrit",
  "Burgers": "Burgeri",
  "Chicken": "Piletina",
  "Traditional cuisine": "Tradicionalna kuhinja",
  "Snack Bar": "Užina bar",
  "Burek": "Burek",
  "Mediterranean": "Mediteranska",
  "Seafood": "Morski plodovi",
  "Crepes": "Palačinke",
  "Salads": "Salate",
  "Desserts": "Dezerti",
  "Vegan": "Veganska",
  "Vegetarian": "Vegetarijanska","The selected tags is invalid.":'Izabrani tagovi nisu dozvoljeni',
'Are you looking for a place for your next meal or do you want to list your restaurant so everyone can see it?':'Tražite pravo mesto za sledeći obrok ili želite da postavite svoj restoran da ga svi vide?','You’re in the right place!':'Na pravom ste mestu!','Browse restaurants' :'Pretražite restorane' , 'Post your restaurant' :'Postavite svoj restoran','The value must be a non-empty string.' : 'Vrednost mora biti tekst koji nije prazan.',"The entered city is not on the list of allowed cities.":'Uneti grad nije na listi dozvoljenih gradova.','Selected tags are not valid.':'Izabrani tagovi nisu validni.'
    },
    cities : ["Ada", "Aleksandrovac", "Aleksinac", "Alibunar", "Apatin", "Aranđelovac", "Arilje", "Babušnica", "Bajina Bašta", "Barajevo", 
    "Batočina", "Bač", "Bačka Palanka", "Bačka Topola", "Bački Petrovac", "Bela Palanka", "Bela Crkva", "Beočin", "Bečej", 
    "Blace", "Bogatić", "Bojnik", "Boljevac", "Bor", "Bosilegrad", "Brus", "Bujanovac", "Valjevo", "Varvarin", 
    "Velika Plana", "Veliko Gradište", "Vitina", "Vladimirci", "Vladičin Han", "Vlasotince", "Voždovac", "Vranje", "Vračar", 
    "Vrbas", "Vrnjačka Banja", "Vršac", "Vučitrn", "Gadžin Han", "Glogovac", "Gnjilane", "Golubac", "Gora", 
    "Gornji Milanovac", "Grocka", "Despotovac", "Dečani", "Dimitrovgrad", "Doljevac", "Đakovica", "Žabalj", "Žabari", 
    "Žagubica", "Žitište", "Žitorađa", "Zaječar", "Zvezdara", "Zvečan", "Zemun", "Zrenjanin", "Zubin Potok", 
    "Ivanjica", "Inđija", "Irig", "Istok", "Jagodina", "Kanjiža", "Kačanik", "Kikinda", "Kladovo", "Klina", 
    "Knić", "Knjaževac", "Kovačica", "Kovin", "Kosjerić", "Kosovo Polje", "Kosovska Kamenica", "Kosovska Mitrovica", "Koceljeva", 
    "Kragujevac", "Kraljevo", "Krupanj", "Kruševac", "Kula", "Kuršumlija", "Kučevo", "Lazarevac", "Lajkovac", 
    "Lapovo", "Lebane", "Leposavić", "Leskovac", "Lipljan", "Loznica", "Lučani", "Ljig", "Ljubovija", "Majdanpek", 
    "Majdanpek", "Mali Zvornik", "Mali Iđoš", "Malo Crniće", "Medveđa", "Mediana", "Merošina", "Mionica", "Mladenovac", 
    "Negotin", "Niška Banja", "Nova Varoš", "Nova Crnja", "Novi Beograd", "Novi Bečej", "Novi Kneževac", "Novi Pazar", "Novi Sad", 
    "Novo Brdo", "Obilić", "Obrenovac", "Opovo", "Orahovac", "Osečina", "Odžaci", "Palilula", "Palilula (Niš)", 
    "Pantelej", "Pančevo", "Paraćin", "Petrovaradin", "Petrovac na Mlavi", "Peć", "Pećinci", "Pirot", "Plandište", 
    "Podujevo", "Požarevac", "Požega", "Preševo", "Priboj na Limu", "Prizren", "Prijepolje", "Priština", "Prokuplje", 
    "Ražanj", "Rakovica", "Rača", "Raška", "Rekovac", "Ruma", "Savski venac", "Svilajnac", "Svrljig", "Senta", 
    "Sečanj", "Sjenica", "Smederevo", "Smederevska Palanka", "Sokobanja", "Sombor", "Sopot", "Srbica", "Srbobran", 
    "Sremska Mitrovica", "Sremski Karlovci", "Stara Pazova", "Stari grad", "Stragari", "Subotica", "Suva Reka", "Surdulica", 
    "Surčin", "Temerin", "Titel", "Topola", "Trgovište", "Trstenik", "Tutin", "Ćićevac", "Ćuprija", "Ub", 
    "Užice", "Uroševac", "Crveni krst", "Crna Trava", "Čajetina", "Čačak", "Čoka", "Čukarica", "Šabac", 
    "Šid", "Štimlje", "Štrpce"
    ],
    tagsEn :[
            'Sandwiches',
            'Food truck',
            'Pub',
            'Bakery',
            'Pizza',
            'Deli',
            'Fine dining',
            'Buffet',
            'Bar',
            'Bar and Brewery',
            'Fast food',
            'Cafeteria',
            'BBQ (Barbecue)',
            'Gyros',
            'Breakfast',
            'Lunch',
            'Dinner',
            'Dine-in',
            'Drive-through',
            'Drinks',
            'Kebab',
            'Indian',
            'Fish',
            'Pasta',
            'Italian',
            'International',
            'Mexican',
            'Thai',
            'Chinese',
            'Japanese',
            'French',
            'French Fries',
            'Burgers',
            'Chicken',
            'Traditional cuisine',
            'Snack Bar',
            'Burek',
            'Mediterranean',
            'Seafood',
            'Crepes',
            'Salads',
            'Desserts',
            'Vegan',
            'Vegetarian'
          ],
    tagsSr : [
      "Sendviči",
      "Kombi sa hranom",
      "Pab",
      "Pekara",
      "Pica",
      "Delikates",
      "Gurmanski restoran",
      "Bife",
      "Bar",
      "Bar i pivara",
      "Brza hrana",
      "Kantina",
      "Roštilj",
      "Giros",
      "Doručak",
      "Ručak",
      "Večera",
      "Jedenje u restoranu",
      "Prolazna usluga",
      "Pića",
      "Kebab",
      "Indijska",
      "Riba",
      "Pasta",
      "Italijanska",
      "Internacionalna",
      "Meksička",
      "Tajska",
      "Kineska",
      "Japanska",
      "Francuska",
      "Pomfrit",
      "Burgeri",
      "Piletina",
      "Tradicionalna kuhinja",
      "Užina bar",
      "Burek",
      "Mediteranska",
      "Morski plodovi",
      "Palačinke",
      "Salate",
      "Dezerti",
      "Veganska",
      "Vegetarijanska"
    ],
    titleValidation : function (value){
      return typeof value === 'string' && value.trim() !== '';
    },
    cityValidation : function (city) {
      return Globals.cities.includes(city.trim());
    
    },
    tagsValidation : function (tags) {
      if ( !Array.isArray(tags) || tags.length == 0 ){
        return false;
      }
      tags.forEach(tag => {
        if ( !Globals.tagsEn.includes(tag.trim())){
          return false;
        }
      });
      return true;
    
    } 
   
  };